// import { PrismaClient } from '@prisma/client';

// export default function Db(props) {
//   return (
//     <div>     
//      {props.sightseeing.map((sightseeings, index) =>
//         <div key={sightseeings.city,sightseeings.place}>
//           {sightseeings.place}
//           {sightseeings.city}
//         </div>
//      )}
//     </div>
//   );
// }

// export async function getServerSideProps() {
//     const prisma = new PrismaClient();

//     const result = await prisma.sightseeing.findMany({
//         where: {
//           city: '伊勢'
//         }
//       });
//     return {
//         props: {
//         sightseeing: result,
//         }
//     };
// }






// import { PrismaClient } from '@prisma/client';

// export default function Db(props) {
//     return (
//       <div>
//        {props.users.map((user, index) =>
//           <div key={user.name,user.memo}>
//             {user.name}は
//             {user.memo}
//           </div>
//        )}
//       </div>
//     );
//   }
  
//   export async function getServerSideProps() {
//       const prisma = new PrismaClient();
  
//       const result = await prisma.users.findMany({
//           where: {
//             memo: '食いしん坊'
//           }
//         });
//       return {
//           props: {
//           users: result
//           }
//       };
//   }





import { useState, useEffect } from 'react';
import styles from '../styles/Main.module.css';
import Head from 'next/head'
import Image from 'next/image';
// import { useRouter } from 'next/router';

export default function AddUser() {
  // const router = useRouter();
  const [SScity, setSScity] = useState('');
  const [SSplace,setSSplace] = useState('');
  const [result, setResult] = useState('');

  const handlerChange = (e) => {
    setSScity(e.target.value);
  };
  const handlerChanges = (e) => {
    setSSplace(e.target.value);
  };
  const handlerClick = (e) => {
    fetch(
      '/api/adds',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          city: SScity,
          place: SSplace
        })
      },
    )
      .then((res) => {
        return res.json();
      })
      .then((json) => {
        setResult('追加しました。');
      });
  };

  return (
    <div>
      <Head>
        <title>Ticket Creater</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <div className={styles.container}>
        <div className={styles.main}>
          <h1>追加</h1>
          <input
            type="text"
            value={SScity}
            onChange={handlerChange}
            placeholder="市町村"
          />
          <input
            type="text"
            value={SSplace}
            onChange={handlerChanges}
            placeholder="観光地名"
          />
          <button onClick={handlerClick}>
            追加
          </button>
        </div>
      </div>
      <div>
      {result}       
      </div>
    </div>
  );
}